version: "3"

services:
  webapp:
    image: soberbot94/cowsay-as-a-service:latest
    ports:
      - 5000
    environment:
      - SERVICE_PORTS=5000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - web

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - webapp
    environment:
      - BALANCE=roundrobin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5001:80
    networks:
      - web
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay
